### ISSUE TITLE
Create a pre-commit hook for Samplr

### ISSUE THREAD

**Issue by geokhoury** [jordanopensource/pre-commit-hooks#1]
- https://github.com/unmultimedio/samplr
- https://github.com/unmultimedio/samplr?tab=readme-ov-file#5-set-up-a-githook-optional
- https://github.com/jordanopensource/pre-commit-hooks

**Comment by thamudi** [comment]
Done in [Latest pre-commit hooks release](https://github.com/jordanopensource/pre-commit-hooks/releases)
